@startuml

!include https://raw.githubusercontent.com/FrankKooij/model/master/opmaak.iuml

hide circle
hide empty members

hide stereotype

hide <<enumeration>>
hide attributes
hide methods

title Semantisch model van NEN 3610:2022

namespace nen3610 {

''    legend "Vergelijk paragraaf 8.4.4.2.1 van NEN 3610:2022."

    GeoObject <|-- ReeelObject : <<Generalisatie>>
    ReeelObject <|-- Bodem : <<Generalisatie>>
    ReeelObject <|-- Oppervlaktewater : <<Generalisatie>>
    ReeelObject <|-- Begroeiing : <<Generalisatie>>
    ReeelObject <|-- Constructie : <<Generalisatie>>
    Constructie <|-- Gebouw : <<Generalisatie>>
    Constructie <|-- Verharding : <<Generalisatie>>
    Constructie <|-- Kunstwerk : <<Generalisatie>>
    Constructie <|-- Leiding : <<Generalisatie>>

    GeoObject <|-- VirtueleRuimte : <<Generalisatie>>
    VirtueleRuimte <|-- FunctioneleRuimte : <<Generalisatie>>
    VirtueleRuimte <|-- RegistratieveRuimte : <<Generalisatie>>
    VirtueleRuimte <|-- GeografischeRuimte : <<Generalisatie>>
    VirtueleRuimte <|-- JuridischeRuimte : <<Generalisatie>>
    FunctioneleRuimte <|-- Transportruimte : <<Generalisatie>>
    Transportruimte <|-- Verkeerruimte : <<Generalisatie>>
    Transportruimte <|-- Waterverplaatsingsruimte : <<Generalisatie>>
    Verkeerruimte <|-- Wegverkeerruimte : <<Generalisatie>>
    Verkeerruimte <|-- Spoorverkeerruimte : <<Generalisatie>>
    Verkeerruimte <|-- Scheepvaartruimte : <<Generalisatie>>
    Verkeerruimte <|-- Luchtvaartruimte : <<Generalisatie>>

    abstract class "Geo-object" as GeoObject <<Objecttype>> {
    }

    abstract class "Reëel object" as ReeelObject <<Objecttype>> {
    }

    abstract class Bodem <<Objecttype>> {
    }

    abstract class Oppervlaktewater <<Objecttype>> {
    }

    abstract class Begroeiing <<Objecttype>> {
    }

    abstract class Constructie <<Objecttype>> {
    }

    abstract class Gebouw <<Objecttype>> {
    }

    abstract class Verharding <<Objecttype>> {
    }

    abstract class Leiding <<Objecttype>> {
    }

    abstract class Kunstwerk <<Objecttype>> {
    }

    abstract class "Virtuele ruimte" as VirtueleRuimte <<Objecttype>> {
    }

    abstract class "Functionele ruimte" as FunctioneleRuimte <<Objecttype>> {
    }

    abstract class "Registratieve ruimte" as RegistratieveRuimte <<Objecttype>> {
    }

    abstract class "Geografische ruimte" as GeografischeRuimte <<Objecttype>> {
    }

    abstract class "Juridische ruimte" as JuridischeRuimte <<Objecttype>> {
    }

    abstract class Transportruimte <<Objecttype>> {
    }

    abstract class Verkeerruimte <<Objecttype>> {
    }

    abstract class Waterverplaatsingsruimte <<Objecttype>> {
    }

    abstract class Spoorverkeerruimte <<Objecttype>> {
    }

    abstract class Wegverkeerruimte <<Objecttype>> {
    }

    abstract class Scheepvaartruimte <<Objecttype>> {
    }

    abstract class Luchtvaartruimte <<Objecttype>> {
    }

}

@enduml
