@startuml

'' --------v-v-v-v-v-v-v-v--------
'' https://www.rijkshuisstijl.nl/organisatiespecifieke-richtlijnen/ministerie-van-binnenlandse-zaken-en-koninkrijksrelaties/deelidentiteit-kerndepartement-bzk
'' https://www.rijkshuisstijl.nl/basiselementen/basiselementen-online/online-kleuren
''
'' # Communicatiekleuren van BZK
'' Het kerndepartement van BZK heeft uit het kleurenpalet van de rijkshuisstijl drie kleuren (elk met tint1 / tint2) gekozen:
'' - Rijksoverheid hemelblauw #007bc7 (#b2d7ee/#d9ebf7)
'' - Rijksoverheid rood #d52b1e (#f2bfbb/#f9dfdd)
'' - Rijksoverheid groen #39870c (#c3dbb6/#e1eddb)
'' Het gebruik van deze kleuren in combinatie met veel wit wordt gestimuleerd.
''
'' # Tinten voor achtergrondkaders, grafieken en tabellen
'' Voor achtergrondkaders, grafieken en tabellen kunnen 7 neutrale grijstinten of tinten van een communicatiekleur in stappen van 20% worden toegepast. Voor tekstachtergrond wordt grijstint1 of communicatiekleur tint2 aanbevolen om aan de contrasteisen voor een goede leesbaarheid te voldoen.
'' - Rijksoverheid grijs 1 #f3f3f3
'' - Rijksoverheid grijs 2 #e6e6e6
'' - Rijksoverheid grijs 3 #cccccc
'' - Rijksoverheid grijs 4 #b4b4b4
'' - Rijksoverheid grijs 5 #999999
'' - Rijksoverheid grijs 6 #696969
'' - Rijksoverheid grijs 7 #535353
''
'' # Online communicatiekleuren
'' - Rijksoverheid paars        #42145f (#c6b8cf/#e3dce7)
'' - Rijksoverheid violet       #a90061 (#e5b2cf/#f2d9e7)
'' - Rijksoverheid robijnrood   #ca005d (#efb2ce/#f7d9e7)
'' - Rijksoverheid roze         #f092cd (#fadef0/#fdeff8)
'' - Rijksoverheid rood         #d52b1e (#f2bfbb/#f9dfdd)
'' - Rijksoverheid oranje       #e17000 (#f6d4b2/#fbead9)
'' - Rijksoverheid donkergeel   #ffb612 (#ffe9b7/#fff4dc)
'' - Rijksoverheid geel         #f9e11e (#fdf6bb/#fefbdd)
'' - Rijksoverheid donkerbruin  #673327 (#d1c1be/#e8e1df)
'' - Rijksoverheid bruin        #94710a (#dfd4b5/#efeada)
'' - Rijksoverheid donkergroen  #275937 (#becdc3/#dfe6e1)
'' - Rijksoverheid groen        #39870c (#c3dbb6/#e1eddb)
'' - Rijksoverheid mosgroen     #777c00 (#d6d7b2/#ebebd9)
'' - Rijksoverheid mintgroen    #76d2b6 (#d6f1e9/#ebf8f4)
'' - Rijksoverheid donkerblauw  #01689b (#cce0f1/#e5f0f9)
'' - Rijksoverheid hemelblauw   #007bc7 (#b2d7ee/#d9ebf7)
'' - Rijksoverheid lichtblauw   #8fcae7 (#ddeff8/#eef7fb)

'' # De ontwerpregels van het Kadaster (huisstijlhandboek, mei 2007)
''
'' - 'Kadaster klassiek groen #007ea9 (basiskleur en tekstkleur)
'' - 'Kadaster wit #ffffff (aanvullende basiskleur)
'' - 'Kadaster zwart #000000 (tekstkleur)
'' - 'Kadaster krachtig geel #d9c900 (accentkleur, minder dan 10%, evt. tekstkleur in voetnoten of bijschriften)
'' - 'Kadaster kobalt #00387d (basiskleur en tekstkleur)
'' - 'Kadaster innovatief blauw #008dc9 (aanvullende basiskleur en tekstkleur)
'' - 'Kadaster krachtig groen #70a426 (accentkleur, minder dan 10%, evt. tekstkleur in voetnoten of bijschriften)
'' - 'Kadaster rood #9c1722 (accentkleur wanneer geel en groen ongeschikt, minder dan 10%, evt. tekstkleur in voetnoten of bijschriften)
''
'' REGELS
'' - Klassiek groen en kobalt vormen de basiskleuren.
'' - Wit en innovatief blauw vullen de basiskleuren aan.
'' - Wit speelt een belangrijke rol; het zorgt voor rust en ruimte op de pagina en vergroot zo de leesbaarheid.
'' - Geel en groen zijn puur accentkleuren; ze worden nooit gebruikt om een groot vlak te vullen.
'' - Maximaal 10% van een uiting mag geel en/of groen zijn.
'' - Teksten mogen worden gezet in klassiek groen, kobalt, innovatief blauw, zwart en diapositief.
'' - Gebruik van krachtig geel en groen in tekst kan alleen bij kleine voetnoten of bijschriften.
'' - Menging tussen kleuren is toegestaan.
'' - Percentages of halftonen zijn niet toegestaan.
'' - De dtp-er mag fotografie zodanig bewerken dat deze de huisstijlkleuren uitstraalt; bijvoorbeeld door een multiply-vlak, een monotoon en duotoon waarbij de kleuren te herleiden zijn.
'' - Vlakverdeling is horizontaal of verticaal; diagonale lijnen voor vlakverdeling zijn niet mogelijk. Diagonaal lijnenspel komt alleen in de vormentaal voor (zie huisstijlhandboek).
'' - Wanneer in digitale uitingen geel of groen als accentkleur niet mogelijk zijn, mag bij hoge uitzondering rood toegepast worden.
''
'(Het huisstijlhandboek doelt met diapositief op een witte voorgrond op fotografie of een achtergrond in een huisstijlkleur.)

'' --------^-^-^-^-^-^-^-^--------

'' dpi-resolutie voor .png:
skinparam dpi 300

skinparam defaultFontColor black
skinparam defaultFontName Lucida Grande, Lucida Sans
skinparam defaultFontSize 11
skinparam defaultFontStyle normal
skinparam defaultMonospacedFontName Menlo, Lucida Sans Typewriter
'' skinparam defaultTextAlignment left
'' skinparam lineType ortho
'' skinparam lineType polyline
skinparam shadowing false
skinparam wrapWidth 165

skinparam class {
    ArrowColor #70a426
    ArrowFontSize 10
''     ArrowTextAlignment center
    ArrowThickness 1.5
''     AttributeFontColor #000000
    AttributeIconSize 0
    BackgroundColor #ffffff
    BorderColor #007bc7
    BorderThickness 2.5
    FontColor #007bc7
    FontSize 12
    FontStyle bold
''     StereotypeFontStyle italic
''     StereotypeFontColor #000000
}

skinparam class<<extern>> {
    AttributeFontColor #b4b4b4
    BorderColor #b4b4b4
    FontColor #b4b4b4
    StereotypeFontColor #b4b4b4
}

skinparam class<<vrijwillig>> {
    BorderThickness 1
    FontStyle normal
    RoundCorner 25
}

skinparam note {
    BackgroundColor #fdeff8
    BorderColor #fadef0
    FontColor #00387d
}

skinparam package {
    BackgroundColor #f3f3f3
    BorderColor #9c1722
    FontColor #9c1722
    FontSize 12
    FontStyle bold
    Style rectangle
}

skinparam package<<subpackage>> {
    BackgroundColor #e6e6e6
    BorderColor #e6e6e6
    FontStyle normal
}

@enduml
