@startuml

!include https://raw.githubusercontent.com/FrankKooij/model/master/opmaak.iuml

hide circle

hide empty members

hide stereotype

hide <<enumeration>>

'' hide attributes

'' hide methods

hide namespace

'' -------------------------------------------------------------------------------------------------

'' hide <<Gestructureerd datatype>>
'' hide <<Referentielijst>>

skinparam wrapWidth 250

'' =================================================================================================

'' title Conceptueel informatiemodel van de praktijkhandleiding

Theme "1" --> "*" Subtheme
Collection "1" *-- "*" Page
'' TagCollection "1" *-- "*" Tag
'' Tag "*\n+ collection\n+ title" <-- "*" Page
Tag "*" <-- "*" Page
'' Tag "0..1" *-- "1" Page
Tag --|> Page
'' Theme <|-- Trefwoorden
Collection <|-- Theme
Collection <|-- Subtheme
'' Site "1" *-- "*" Collection
'' Site "1" .. "*" Page

'' abstract class Site <<Objecttype>> {
''     + config: Config [1..1]
'' }

'' class Config <<Gestructureerd datatype>> {
''     --
''     _config.yml
'' }

abstract class Collection <<Objecttype>> {
    + name: CharacterString [1..1]
    + alias: CharacterString [0..1]
    + dates: Boolean [1..1]
''    + origin [0..1]
    + output: Boolean [1..1]
    + tagLists: Boolean [1..1]
    + zoeken: Boolean [1..1]
    --
Set of pages that describe similar things.
}

Collection "*" --> "+ origin\n0..1" Collection

class Layout <<Objecttype>> {
    + script [0..1]
--
Content structure that enhances the body of a page.
}

class Default <<Objecttype>> {
Core content structure of the body of a page.
}

abstract class Theme <<Objecttype>> {
}

Page "*" --> "+ file name\n1" Layout

Layout "*" -> "+ file name\n0..1" Layout

Collection "0..1" -- "0..1" Layout

Layout "1" -- "0..1" Theme

Default "*" --> "+ file name\n0" Layout

Default --|> Layout

Template "*" --> "1" Layout

Template "0..1" -- "1" Collection

Page "*" --> "1" Theme

'' Page::toc "1" -> "1" Page::content


class Template <<Objecttype>> {
    + collectionSortOrder: SortOrder [1..1]
    + showNoDateItems: Boolean [1..1]
    + menuSortCode: CharacterString [0..1]
    + title: CharacterString [1..1]
    --
    Content structure for an index page.
}

class Page <<Objecttype>> {
    + content [1..1]
    + date: yyyy-mm-dd [0..1]
    + description: CharacterString [0..1]
    + editor: CharacterString [0..1]
    + mermaid: Boolean [0..1]
    + sortCode: CharacterString [0..1]
    + title: CharacterString [1..1]
''     + toc: Toc [0..1]
    + toc [0..1]
    --
    The body text of the web page (encoded as Kramdown) with meta data (encoded as YAML front matter).
''    De romptekst van de webpagina (in Kramdown) met YAML front matter.
    --
    Layout hoort eigenlijk thuis bij collection
}

class Snippet <<Objecttype>> {
    + content [1..1]
    + title: CharacterString [1..1]
    --
    Text snippet (encoded as Kramdown) with meta data (encoded as YAML front matter).
'' Tekstfragmenten
}

Page "*" -> "+ title\n*" Snippet
Snippet "*" -> "+ title\n*" Snippet
Collection "1" *-- "*" Snippet

abstract class Subtheme <<Objecttype>> {
}

'' class Toc <<Gestructureerd datatype>> {
''     + koptekst [1..*]
''     --
''     Selectieve lijst van letterlijk overgenomen hoofdstuk- en paragraaftitels uit de content, die samen de basis vormen voor een navigeerbare inhoudsopgave.
'' }

'' abstract class TagCollection <<Objecttype>> {
'' }

'' TagCollection --|> Collection

abstract class Tag <<Objecttype>> {
''     + name [1..1]
}

'' class Trefwoorden <<Objecttype>> {
'' }

NamedCollection --|> Collection

NamedCollection "1" *-- "*" Tag

'' Beleidskaders --|> Collection
'' Gebeurtenissen --|> Collection
'' Modeldocumenten --|> Collection
'' Objecttypen --|> Collection
'' Relaties --|> Collection
'' Trefwoorden --|> Collection

class SortOrder <<Referentielijst>> {
    + alphabetical
    + chronological
    + sortCode
}

@enduml
