'' PlantUML Class Diagram

@startuml

skinparam defaultFontColor black
skinparam defaultFontName Lucida Sans
skinparam defaultFontSize 11
skinparam defaultFontStyle normal
skinparam shadowing false
skinparam wrapWidth 250
skinparam class {
    ArrowColor #70a426
    ArrowFontSize 10
    ArrowThickness 1.5
    AttributeIconSize 0
    BackgroundColor #ffffff
    BorderColor #007bc7
    BorderThickness 2.5
    FontColor #007bc7
    FontSize 12
    FontStyle bold
}

hide circle
hide empty members
'' hide attributes
'' hide methods
hide namespace
'' hide stereotype

'' hide Site
hide Snippet
hide <<Gestructureerd datatype>>
hide <<Referentielijst>>

'' =================================================================================================

title Conceptual information model for publishing linked data-specification details on the web using Jekyll as a static site generator

Site "1" *-- "1..*" Collection
Site "1" *-- "1..*" IndexLayout
Site "1" *-- "1..*" Layout

Collection "1" *-- "*" Document
Collection "*" --> "+ origin\n0..1" Collection

Document "*" --> "+ layout\n1" Layout
Document "*" --> "+ subDocCollection\n0..1" Collection

Tag "*" <--> "*" Document
Tag "*"   -> "1" Collection
Tag --|> Document

Layout "*" --> "+ harvest\n0..1" Collection
Layout "1" --> "+ filter\n0..1" Collection
Layout "*" --> "+ layout\n0..1" Layout

IndexLayout --|> Layout
IndexLayout "*" --> "+ layout\n1" Layout
IndexLayout "0..1" --> "+ harvest\n1" Collection

Collection  "1" *.. "*" Snippet
Document    "*" ..> "*" Snippet
IndexLayout "*" ..> "*" Snippet
Layout      "*" ..> "*" Snippet
Snippet     "*" ..> "*" Snippet

abstract class Site <<Objecttype>> {
    + baseURL: CharacterString [1..1] {classifier}
    + license: CharacterString [1..1]
''    --methods--
''    --definition--
''    --constraints--
''    --encoding--
}

class Collection <<Objecttype>> {
    + label: CharacterString [1..1] {classifier}
    + alias: CharacterString [0..1]
    + includeInSearch: Boolean [1..1]
    + showDates: Boolean [1..1]
    + output: Boolean [1..1]
    + useAsTags: Boolean [1..1]
''    --methods--
    --definition--
    Set of documents that describe similar concepts
''    --constraints--
''    --encoding--
}

class Document <<Objecttype>> {
    + title: CharacterString [1..1] {classifier}
''    + collection {classifier}
    + content: CharacterString [1..1]
    + date: Date [0..1]
    + description: CharacterString [0..1]
    + editor: CharacterString [0..1]
    + hasDiagrams: Boolean [0..1]
    + sortCode: CharacterString [0..1]
    + toc: TableOfContents [0..1]
''    --methods--
    --definition--
    The text for the body of a page with its metadata
    --constraints--
    + title must be unique within the collection
    + sortCode for the collection index must be either unique or empty for all documents in the collection
    + a document should not tag itself
    + subDocCollection is required if a document is the parent of subdocuments
    + all subdocuments to a document must be in the same collection
    --encoding--
    Kramdown with YAML front matter (and sometimes Mermaid diagrams or Liquid or both)
}

abstract class Tag <<Objecttype>> {
''    --methods--
    --definition--
    Document in a taggable collection
''    --constraints--
''    --encoding--
}

class Layout <<Objecttype>> {
    + fileName [1..1] {classifier}
    + showSubDocs: Boolean [0..1]
    --methods--
    contentWrapper()
    --definition--
    Content template for the body of a page
    --constraints--
    + non-default layouts must link to a layout
    + the base default layout must not link to any layout
    + a layout must not link to itself
    + a filter relation requires also a harvest relation
    --encoding--
    HTML with Liquid and YAML front matter
}

class IndexLayout <<Objecttype>> {
    + title: CharacterString [1..1] {classifier}
    + collectionSortOrder: SortOrder [1..1]
    + hasDiagrams: Boolean [0..1]
    + siteMenu: Boolean [0..1]
    + sortCode: CharacterString [1..1]
    + showNoDateItems: Boolean [1..1]
''    --methods--
    --definition--
    Layout for the index page of a root collection
    --constraints--
    + sortCode for site menu must be unique
''    --encoding--
''    HTML with Liquid and YAML front matter
}

class Snippet <<Objecttype>> {
    + title: CharacterString [1..1] {classifier}
    + content: CharacterString [1..1]
''    --methods--
    --definition--
    Text snippet with its metadata
''    --constraints--
    --encoding--
    Kramdown with YAML front matter (and sometimes Mermaid diagrams or Liquid or both)
}

class TableOfContents <<Gestructureerd datatype>> {
    + heading: CharacterString [1..*]
''    --methods--
    --definition--
    Selected exact quotations of content headings for a navigable table of contents in the sidebar
''    --constraints--
    --encoding--
    YAML sequence
}

class SortOrder <<Referentielijst>> {
    + alphabetical
    + chronological
    + sortCode
''    --methods--
    --definition--
    Valid choices for the order in which a list of navigable links is presented
''    --constraints--
''    --encoding--
}

@enduml
